version: "3.0"

services:
    unittests:
        image: webserver
        build: 
            context: ./
            dockerfile: ./deploy/webserver/Dockerfile
        environment: 
            - DATAPATH=/var/www/cs-train
        volumes: 
            - ./:/var/www
        command: "sh -c 'python -m unittest unittests/*.py -vvv'"

    webserver:
        image: webserver
        depends_on: 
            - unittests
        build: 
            context: ./
            dockerfile: ./deploy/webserver/Dockerfile
        restart: always
        environment: 
            - PORT=5000
            - DATAPATH=/var/www/cs-production
        volumes: 
            - ./:/var/www
        ports:
            - "80:5000"
        command: "sh -c 'python run_data_ingestion.py && python wsgi.py'"

    # notebooks:
    #     image: notebooks
    #     build: 
    #         context: ./
    #         dockerfile: ./deploy/notebooks/Dockerfile