version: "3.0"

services:
    unittests:
        image: webserver
        build: 
            context: ./
            dockerfile: ./deploy/webserver/Dockerfile
        environment: 
            - DATAPATH=/var/www/data/cs-train
        volumes: 
            - ./:/var/www
        command: "sh -c 'python -m unittest unittests/*.py'"

    webserver:
        image: webserver
        depends_on: 
            - unittests
        build: 
            context: ./
            dockerfile: ./build/webserver/Dockerfile
        restart: always
        environment: 
            - PORT=5000
            - DATAPATH=/var/www/data/cs-production
        volumes: 
            - ./:/var/www
        ports:
            - "80:5000"
        command: "sh -c 'python run_data_ingestion.py && python wsgi.py'"
